sudo: false
dist: focal
branches:
  only:
    - master
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/poetry
    - $HOME/.cache/pre-commit
addons:
  apt:
    packages:
      - sqlite3

language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
before_install:
- sqlite3 --version
- pip install poetry
install:
- poetry install
script:
- make test

after_success:
- curl -Os https://uploader.codecov.io/latest/linux/codecov
- chmod +x codecov
- ./codecov -t ${CODECOV_TOKEN}

