dist: xenial
sudo: false
branches:
  only:
    - master
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
addons:
  apt_packages:
    - sqlite3

language: python
python:
  - "3.9"
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run pytest

after_success: coveralls
