sudo: false
dist: focal
branches:
  only:
    - master
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/poetry
    - $HOME/.cache/pre-commit
addons:
  apt:
    packages:
      - sqlite3

language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
env:
  matrix:
    - TOXENV=py39-django32
    - TOXENV=py310-django32
    - TOXENV=py311-django32
    - TOXENV=py312-django32
    - TOXENV=py39-django42
    - TOXENV=py310-django42
    - TOXENV=py311-django42
    - TOXENV=py312-django42
    - TOXENV=py39-djangolatest
    - TOXENV=py310-djangolatest
    - TOXENV=py311-djangolatest
    - TOXENV=py312-djangolatest
install:
  - pip install tox
script:
  - tox -e $TOXENV

after_success:
- curl -Os https://uploader.codecov.io/latest/linux/codecov
- chmod +x codecov
- ./codecov -t ${CODECOV_TOKEN}
